version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./es7/logs:/usr/share/elasticsearch/logs
      - ./es7/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  oap:
    image: apache/skywalking-oap-server:7.0.0-es7
    container_name: oap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./skywalking-oap/config/application.yml:/skywalking/config/application.yml
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
  ui:
    image: apache/skywalking-ui:7.0.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
  kibana:
    image: hub.c.163.com/nesonlinetest/kibana/kibana-oss:7.5.0
    container_name: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 5601:5601
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./kibana/config/kinaba.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
networks:
  default:
    external:
      name: sky-network
